### ISSUE TITLE
Does jupyter server support unix sockets?

### ISSUE THREAD

**Issue by goanpeca** [jupyter-server/jupyter_server#307] opened 2020-09-16 14:12 UTC
From Discourse:

>@mlucool 
>Hi,  Does jupyterlab support unix sockets? If so, how do I configure it?  It seems Notebook supports them (https://jupyter-notebook.readthedocs.io/en/stable/changelog.html#release-6-1-0) and tornado does too (https://github.com/tornadoweb/tornado/issues/2671). If this feature is missing, which is the right repo to log an issue for this, jupyter_server?

**Comment by kevin-bates** [comment] 2020-09-16 14:30
Hi Gonzalo,
The [sockets PR](https://github.com/jupyter/notebook/pull/4835) is on the [list of pull requests to port over from Notebook](https://github.com/jupyter/jupyter_server/issues/110) - time just hasn't been very cooperative.

Since this is purely a server issue, I took the liberty of updating the title since I believe you meant to say 'jupyter server' anyway.  (If not, you _could_ have unix sockets in jupyterlab by using lab 2.x since that still uses the notebook server if I'm not mistaken.)

**Comment by goanpeca** [comment] 2020-09-16 14:32
Thanks for the update @kevin-bates 

>I believe you meant to say 'jupyter server' 

Yes :-p

**Comment by PromyLOPh** [comment] 2021-05-18 10:33
Is anyone working on porting the feature from Notebook right now? We’re stuck on JupyterLab v2, because v3.0 essentially removed this feature.

**Comment by kevin-bates** [comment] 2021-05-18 15:08
Good point on the perceived regression issue.  I believe this was being worked on (on the side) but, IIRC, a snag was hit relative to converting the tests to `pytest`. 

Looking at the list of PRs to port from Notebook, it looks like this effort would consist of the following...

jupyter/notebook#4835 (includes jupyter/notebook#5650, jupyter/notebook#5451, jupyter/notebook#5769)

**Comment by PromyLOPh** [comment] 2021-05-18 16:14
Is there a branch with the current progress somewhere? Maybe we can figure this out together.

**Comment by Zsailer** [comment] 2021-05-20 21:51
See #525.

**Comment by Zsailer** [comment] 2021-05-25 17:44
Merged in #525. 🚀

**Closed** 2021-05-25 17:44 UTC

**Comment by PromyLOPh** [comment] 2021-05-26 06:03
That was quick, thank you very much!
