### ISSUE TITLE
RFP for successor to data_files-based extension discovery?

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-server/jupyter_server#351] opened 2020-11-21 04:36 UTC
> @blink1073  I'm saying support both. I personally would be happy to never use data_files again unless their level of support changes. - https://github.com/jupyter-server/jupyter_server/issues/224#issuecomment-632730340

The threshold of "change" is met, but not in not the way suggested, and not looking better in 2021, with changes coming to pip, setuptools, etc. 

Maybe it's time to open something akin to a requests for proposals for ways forward?

It would appear the viability is falling of `data_files` as a way for python projects to ship extension assets, e.g. js/css, kernelspecs, and configuration, e.g. jupyter_config. I think we need to think about some ways that we can appease:
- ease of distribution of core jupyter packages' assets
- ease of installation of the "official" jupyter packages (which I guess is a python sdist/whl) 
- ease of re-distribution via "unixy" package managers (e.g. `conda`, `brew`, `apt`), etc. as that may be able to preserve some of the current end user experience

I've some ideas, but would love to hear out some more thoughts! Oh, and if this belongs somewhere else, please let me know... I'm sure at some point this will end up having to have a JEP-level clarification, but...

**Comment by SylvainCorlay** [comment] 2020-11-21 06:21
I think that data files is still the way to go, as it provides a very clear API to manage content under `PREFIX/share` and `PREFIX/etc`.

**Comment by maartenbreddels** [comment] 2020-11-21 06:32
I'm wondering what the issue is, did something change recently? I don't see
data_files disappearing (it would break the python ecosystem). If dev
installs are a problem, I think we can solve that.

(from mobile phone)

**Comment by bollwyvl** [comment] 2020-11-21 13:40
This really only affects the mainline python packaging/installation...
conda, etc. don't care at all about these issues, and can continue to be
shipped how they do. And certainly other languages need to be able to rely
on share/etc. But getting down to it, we're in python land, and are pretty
much ruled by whatever comes down the pipe.

No doubt users will be able to continue to install artifacts that include
data_files... for now. but creating the stuff is getting harder. And
pinning to older "pip" or even "setuptools" doesn't seem like a great
option if one of them drops it, or requires an end user flag.

My concern is that with the pace of breakage in the mainline tools (e.g new
pip solver vs extras) is going to make it difficult to make it easy for
packages to casually offer jupyter integration... Everything's going to
have to be a "jupyter-" this and "jupyter_" that because jupyter packages
will look so different from what official documentation suggests.

For example, taking a peep at the suggested cookiecutter setup for lab3
extensions seems very complex, when without data_files we could likely
encourage a single pyproject.toml (or setup.cfg+1 line setup.py) and be
done with it... and get better metadata, e.g. data_files didn't make the
cut on pep 621:
https://www.python.org/dev/peps/pep-0621/

**Comment by bollwyvl** [comment] 2020-11-21 21:03
This [draft PR](https://github.com/jupyter/jupyter_core/pull/209) shows one way forward which would be compatible with just about everything, require very few downstream changes, and only uses PEP 621-compliant meta data.

**Comment by maartenbreddels** [comment] 2020-11-21 21:31
I like it Nick, indeed I agree with many points you bring up, and it's making me a bit sad(I see data_files as super duper fundamental), but your solution makes me a bit happier. I'll comment more in your pr.

**Comment by bollwyvl** [comment] 2021-01-30 17:45
Still feeling the pain on this. 

Turns out having files in-tree and in data_files leads to them being shipped _twice_. For "a little python" or whatever, this is no big deal. For shipping [ipydrawio](https://pypi.org/project/ipydrawio/#files), however, which is a full data-drive design tool, the `whl` is currently sitting just under 70mb, and expands to ~200mb (lots of un-compressed XML, twice). The sdist is 30mb, because `tar.gz` is apparently smarter than `whl`, but _still_ unpacks to the same size.

**Comment by layne-sadler** [comment] 2021-03-10 17:38
Does `appdirs` apply here? Looks like Sublime is using it for packages.

![image](https://user-images.githubusercontent.com/76759666/110672303-e36b9e80-81a5-11eb-865d-db39541b9f95.png)

**Comment by blink1073** [comment] 2022-01-15 22:06
Hmm, it seems like at that point we'd be better off wrapping flit to add a build step in jupyter-packaging.   And server extensions with no build step could just use flit directly.

**Comment by blink1073** [comment] 2023-01-08 20:47
Closing this, since we've settled on using `shared_data` from `hatch`.

**Closed by blink1073** 2023-01-08 20:47 UTC

**Comment by bollwyvl** [comment] 2023-01-08 23:17
Yes, we needn't change anything on this repo (or `jupyter_core`), as kernel (see [below](#aside-about-kernelspecs)), extension, and other tool authors today have the option of declaring this in `pyproject.toml` for any number of [PEP 517](https://peps.python.org/pep-0517/) build backends:
- [`tool.hatch.build.targets.wheel.shared-data`](https://hatch.pypa.io/dev/plugins/builder/wheel/#configuration) without support caveat
- [`tool.flit.external-data`](https://flit.pypa.io/en/stable/pyproject_toml.html#external-data-section) without support caveat
- [`tool.setuptools.data-files`](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration), though marked _**Discouraged**_... but not _**Deprecated**_

A cursory check reveals `poetry` and `maturin` still lack this feature... the former bothers me _not one bit_, but the latter could eventually become a concern.

Perhaps we can dream of a future where  _PEP XXX: Prefix Data_ (as [621](https://peps.python.org/pep-0621/) has disowned this problem) clarifies this so it can move into a single `pyproject.toml#project` field (e.g. `project.prefix-data`) with defined `--editable` behavior, instead of 10 different things with different data models. :sleeping:  :cloud: 

### Aside: about kernelspecs

On a partial tangent, regarding `kernelspecs`: `jupyter_*` (specifically `client`, perhaps) _could_ improve the situation for reproducible, minimal distributions. Specifically, selecting data formats/syntaxes that are more cross-platform, and therefore tolerant to string replacement, would help. The worst case is JSON kernelspec files with respect to paths, especially on windows, which have been a long-standing source of problems.

In light of the above:
- use more normalized URIs to avoid windows paths, e.g. `file:///c:/prefix-placeholder`
- [TOML](https://github.com/ipython/traitlets/pull/649) might also be a reasonable format, as it supports python-style triple (single) quotes, e.g. `'''`
